name: Bug Report
description: File a bug report
title: "bug: "
labels: ["bug"]
assignees:
  - probablyarth
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Explain what happened
      placeholder: the page crashed :flushed:
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: What was expected
      placeholder: the page shouldn't have crashed :grin:
    validations:
      required: true
